import type { NextPage } from "next";
import Head from "next/head";
import ReactCardFlip from "react-card-flip";
import { useState } from "react";
import axios from "axios";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Country Service App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center content-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Country <span className="text-purple-300">Service</span> App
        </h1>
        <p className="text-2xl text-gray-700">Which country would you like to know about?:</p>
        <div className="mt-3 gap-3 w-80 pt-3 text-center">
          <CountryCard name="Finland" countryCode="FI" capital="Helsinki" population={6000000} flagURL="www.flag.com"
            />
          </div>
      </main>
    </>
  );
};

export default Home;

type CountryCardProps = {
  name: string;
  countryCode: string;
  capital: string;
  population: number;
  flagURL: string;
};

const CountryCard = ({
}: CountryCardProps) => {
  const [countryName, setCountryName] = useState('');
  const [countryCode, setCountryCode] = useState('');
  const [capital, setCapital] = useState('');
  const [population, setPopulation] = useState(0);
  const [flagURL, setFlagURL] = useState('');
  const [isFlipped, setIsFlipped] = useState(false);

  const handleClick = (e: { preventDefault: () => void; }) => {
    e.preventDefault();
    setIsFlipped((prev => !prev) )
  }

  const fetchCountryInformation = (event: any) => {
    event.preventDefault();
    axios.get(`http://localhost:8080/countries/${countryName}`)
      .then((response) => {
        console.log(response.data)
        setCountryCode(response.data.code)
        setCapital(response.data.capital)
        setPopulation(response.data.population)
        setFlagURL(response.data.flagURL)
      })
    setIsFlipped((prevState => !prevState))
  }

  return (
    <ReactCardFlip isFlipped={isFlipped} flipDirection='horizontal'>
      <div>
        <section
          className="flex flex-col justify-center content-center rounded border-2 border-gray-500 p-6 shadow-xl duration-500 motion-safe:hover:scale-105">
          <h2 className="text-lg text-gray-700">Enter country name</h2>
          <form onSubmit={fetchCountryInformation}>
            <input
              className="bg-gray-50 border border-gray-300 text-gray-700 text-sm rounded-lg focus:ring-purple-500 focus:border-purple-500 block w-full p-2.5 dark:bg-purple-300 dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-700 dark:focus:ring-purple-500 dark:focus:border-purple-500"
              type="text"
              onChange = {(e) => setCountryName(e.target.value)} value = {countryName}/>
            <button onClick={fetchCountryInformation}
                    className="my-1 text-white bg-gray-500 hover:bg-gray-600 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-gray-500 dark:hover:bg-gray-600 dark:focus:ring-gray-800"
                    type="submit">Submit
            </button>
          </form>
        </section>
      </div>
      <div onClick={handleClick}>
        <section
          className="flex flex-col justify-center content-center rounded border-2 border-gray-500 p-6 shadow-xl duration-500 motion-safe:hover:scale-105">
          <h2 className="text-lg text-gray-700">{countryName.charAt(0).toUpperCase() + countryName.slice(1)}</h2>
          <p className="text-sm text-gray-600">Country code: {countryCode}</p>
          <p className="text-sm text-gray-600">Capital city: {capital}</p>
          <p className="text-sm text-gray-600">Population: {population}</p>
          <p className="text-sm text-gray-600 flex flex-col justify-center content-center items-center">
            Flag:
            <img
            src={flagURL}
            alt={"Flag of " + countryName}
            width={70}
            height={50}
            />
          </p>
        </section>
      </div>
    </ReactCardFlip>
  );
};
